### ISSUE TITLE
Add 1.0 to GitHub tags/releases

### ISSUE THREAD

**Issue by jayvdb** [bjoernricks/python-quilt#24]

**Comment by bjoernricks** [comment]
Sorry seem I completely did forget about creating a tag :disappointed: 

https://github.com/bjoernricks/python-quilt/releases/tag/1.0

**Comment by jayvdb** [comment]
wow. quick turn around. and I see a new sdist is coming too .. ? ;-)

If so, I'll packaging this up for openSUSE.  They are big fans of the original.  Hopefully they like the py rewrite.

**Comment by bjoernricks** [comment]
Uh cool that would be great. It wasn't intended as a rewrite. Just a verrsion with a python api :smile: I've started this project a long time ago and didn't even get to announce it at the quilt mailing list. Let me know if something isn't working etc.

Btw. do you need a new sdist (and therefore a new release) on pypi too?

**Comment by jayvdb** [comment]
Not needed atm.  I'll package based on the github tag tgz, and let you know how I go.

**Comment by jayvdb** [comment]
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-python-quilt

I'll use it for a while before submitting it to the main repos.
